# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Topic.create(name: 'foreign policy')
Topic.create(name: 'personal')
Topic.create(name: 'taxes')
Topic.create(name: 'corporations')
Topic.create(name: 'military')
Topic.create(name: 'retirement')
Topic.create(name: 'health care')
Topic.create(name: 'infrastructure')
Topic.create(name: 'other')
Topic.create(name: 'unions')
Topic.create(name: 'jobs')
Topic.create(name: 'loopholes')
Topic.create(name: 'income inequality')
Topic.create(name: 'homelessness')
Topic.create(name: 'terrorism')
Topic.create(name: 'budgets')
Topic.create(name: 'states')
Topic.create(name: 'federal')
Topic.create(name: 'corruption')
Topic.create(name: 'climate change')
Topic.create(name: 'immigration')
Topic.create(name: 'prisons')
Topic.create(name: 'justice')
Topic.create(name: 'reform')
Topic.create(name: 'wall street')
Topic.create(name: 'equal rights')
Topic.create(name: 'lgbt')
Topic.create(name: 'education')
Topic.create(name: 'campaign finance')
Topic.create(name: 'citizens united')
